# https://aka.ms/yaml

trigger:
  branches:
    include: [ master, release-* ]

# Global Variables:
#
# version.<generated build number> gets set in a variable called VersionString.
#   VersionString is used to replace placeholders in module file.
#
# isPrerelease controls whether the release artifacts on GitHub and the PowerShell module
#   in the PowerShell Gallery is marked as prerelease or not.
#
variables:
  version: "1.0"
  isPrerelease: ${{ true }}
  isReleaseBranch: $[ or( eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release-') ) ]
  shouldPublishModule: $[ eq( variables.isReleaseBranch, true ) ]

jobs:
- job:
  displayName: "Windows - PowerShell Gallery"
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: PowerShell@2
    inputs:
      targetType: filePath
      failOnStderr: true
      filePath: $(System.DefaultWorkingDirectory)\versionnumber.ps1
      arguments: $(version) $(Build.BuildId)
    displayName: 'Setting build version'

  - task: PowerShell@2
    inputs:
      targetType: inline
      failOnStderr: true
      script: |
        Write-Host "PSModulePath = $($env:PSModulePath)"
        $local:TargetDir = (($env:PSModulePath -split ';') | Where-Object { Test-Path $_ })[0]
        if (-not $TargetDir)
        {
          throw "Unable to find a PSModulePath in your user profile (" + $env:UserProfile + "), PSModulePath: " + $env:PSModulePath
        }
        $local:TargetDir = (Resolve-Path $local:TargetDir)
        Write-Host "ModuleDir = $($local:TargetDir)"
        Write-Output "##vso[task.setvariable variable=ModuleDir;]$($local:TargetDir)"
    displayName: 'Find PowerShell module path'
    condition: succeeded()

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'env | sort'
    displayName: 'Display environment variables'

  - task: PowerShell@2
    inputs:
      targetType: filePath
      filePath: $(System.DefaultWorkingDirectory)\install-forpipeline.ps1
      arguments: $(ModuleDir) $(VersionString) $$(isPrerelease)
    displayName: 'Building PowerShell module'
    condition: succeeded()

  - task: PowerShell@2
    inputs:
      targetType: inline
      failOnStderr: true
      script: |
        Import-Module -Name safeguard-discovery -Verbose
        Get-PSRepository
    displayName: 'Ensure that PowerShell module loads'
    condition: succeeded()
        
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(ModuleDir)\safeguard-discovery'
      includeRootFolder: true 
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    displayName: 'Archiving Powershell module'
    condition: and(succeeded(), eq(variables.isReleaseBranch, true))

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'SafeguardDiscoveryModule'
    displayName: 'Publishing the artifacts'
    condition: and(succeeded(), eq(variables.isReleaseBranch, true))

  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'OneIdentity.RD.SBox.Safeguard-ServiceConnection'
      KeyVaultName: 'SafeguardBuildSecrets'
      SecretsFilter: 'PowerShellGalleryApiKey'
    displayName: 'Get PowerShell Gallery API key from Sandbox Azure Key Vault'
    condition: and( succeeded(), eq( variables.shouldPublishModule, true ) )

  - task: PowerShell@2
    inputs:
      targetType: inline
      failOnStderr: true
      script: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 
        Install-PackageProvider Nuget â€“Force
        Get-PSRepository
        Publish-Module -Name safeguard-discovery -NuGetApiKey "$(PowerShellGalleryApiKey)" -Verbose -SkipAutomaticTags -Force
    displayName: 'Publish PowerShell module to PowerShell Gallery'
    condition: and( succeeded(), eq( variables.shouldPublishModule, true ) )